# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
      
version: 2
updates:
  # Gerenciador de dependências (Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "jocile"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-seguro:
        patterns: ["*"]        
        update-types:
          - "patch"
          - "minor"
      npm-major-risk:
        patterns: ["*"]
        exclude-patterns:
          - "rimraf"
          - "glob"
          - "@11ty/eleventy-plugin-rss"
        update-types:
          - "major"
    # Regras de exceção (Ignore)
    ignore:
      - dependency-name: "@sindresorhus/slugify"
        # Ignora todas as atualizações para o slugify (útil se estiver travado em uma versão CommonJS, por exemplo)
      - dependency-name: "@11ty/eleventy-plugin-rss"
        versions: ["^1.2.0"]
        # Ignora atualizações específicas que correspondam a ^1.2.0

  # Manutenção de workflows e CI/CD
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "jocile"
